version: '3'
services: 
    web:
        image: nginx
        container_name: nginx-example
        ports: 
            - "80:80"
        volumes:
            - "./conf.d:/etc/nginx/conf.d/"
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./htdocs:/usr/share/nginx/html"

#version: '3'
#services:
#  nginx: 
#    container_name: nginx_example
#    build:
#      context: ./nginx-build
#      args:
#        - USER_ID=1000
#        - GROUP_ID=1000
    #volumes:
      # - ./log:/var/log/nginx
      #- ./cache:/var/cache/nginx
      #- ./conf:/etc/nginx
      #- ./share:/usr/share/nginx
#    ports:
#      - 80:8080