version: "2"

# Levantar postgres primero
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - postgres_default
    environment:
      - sonar.jdbc.username=admin
      - sonar.jdbc.password=123
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/admin
    volumes:
      - ~/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - ~/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ~/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
    ulimits:
      nofile:
       soft: 65536
       hard: 65536

networks: 
    postgres_default:
        external: true

# Error sonarquebe al levantar:  sudo sysctl -w vm.max_map_count=262144
