version: '3'
services: 
    web:
        image: nginx
        container_name: nginx-server-files
        ports: 
            - "80:80"
        volumes:
            - "./conf.d:/etc/nginx/conf.d/"
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./htdocs:/usr/share/nginx/html"