# Use root/example as user/password credentials
version: '3'

services:
  mongodb:
    image: mongo
    #restart: always
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports: 
      - 27017:27017
    volumes: 
      - ~/mongodb/mongod.conf:/etc/mongod.conf
      - ~/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ~/mongodb/data/db/:/data/db/
      - ~/mongodb/data/log/:/var/log/mongodb/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: test
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin