version: '3'
services:
  nginx: 
    build: .
    container_name: nginx_opengrok
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/log:/var/log/nginx
      - ./var/cache:/var/cache/nginx
    ports:
      - 80:8080

networks:
  default:
    external:
      name: docker-opengrok_default
