version: '3'
services:
  nginx: 
    build: .
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80

networks:
  default:
    external:
      name: montar-opengrok_default
