version: '3'

services:
  mysql:
    image: mariadb
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: 
      - 3306:3306
    volumes: 
        - ./init:/docker-entrypoint-initdb.d  
        - ~/mariadb/database:/var/lib/mysql