version: "2"

services:
  postgres:
    image: postgres
    # restart: always
    ports:
      - "5432:5432"
    # networks:
    #   - nginx-server_default
    # Este es el usuario root de la base de datos
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - ~/postgres/postgresql:/var/lib/postgresql
      - ~/postgres/postgresql_data:/var/lib/postgresql/data

# networks: 
#     nginx-server_default:
#         external: true